### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by benjaminmaccini** [benjaminmaccini/go-vote#1]
This is a Roadmap for the service. Note that it is in pre-alpha at this point (which really doesn't mean much other than it just doesn't work).

---

- [x] Input validation
- [ ] Better CLI args // config file input (viper)
- [ ] Add TLS
- [ ] Ranked choice
- [ ] Multi member constituency methods
- [ ] Concurrent elections
- [ ] Code cleanup + better logging
- [ ] v0.1.0 release (versioning major.minor.patch)

---

- [ ] Add [cryptographic tallying](http://security.hsr.ch/msevote/seminar-papers/HS09_Homomorphic_Tallying_with_Paillier.pdf)
- [ ] Digital Signatures (multisignature?)
- [ ] v1.0.0 Release

---

- [ ] Verifiable server state (version the same between server-client? Non-malicious server accepting votes?)
